name: build

on:
  push:
jobs:
  build:
    name: Build wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          python -m pip install --no-cache-dir wheel
          python -m pip install --no-cache-dir -r badlands/requirements.txt
          conda install -c msys2 m2w64-toolchain libpython
      - name: Show libraries
        run: |
          python -m pip freeze
      - name: Build wheel
        run: |
          cd badlands
          python setup.py bdist_wheel  --compiler==mingw32
      - name: Install wheel
        if: matrix.os != 'windows-latest'
        run: |
          cd badlands
          python -m pip install dist/*.whl
          python -c "import badlands;print(dir(badlands))"
      - name: Install wheel [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd badlands
          $whl = Get-ChildItem -Path dist -Filter *.whl | Select-Object -First 1
          python -m pip install "$whl"
          python -c "import badlands;print(dir(badlands))"
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: badlands_wheel
          path: badlands/dist/*.whl
