name: build

on:
  push:
jobs:
  build:
    name: Build wheel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          python -m pip install --no-cache-dir wheel
          python -m pip install --no-cache-dir -r requirements.txt
      - name: Show libraries
        run: |
          python -m pip freeze
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
      - name: Install wheel
        if: matrix.os != 'windows-latest'
        run: |
          python -m pip install dist/*.whl
          python -c "import badlands;print(dir(badlands))"
      - name: Install wheel [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          $whl = Get-ChildItem -Path dist -Filter *.whl | Select-Object -First 1
          python -m pip install "$whl"
          python -c "import badlands;print(dir(badlands))"
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: badlands_wheel
          path: dist/*.whl
